### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bertilxi** [bertilxi/Olimpo#1]
### Planificación Release
- [x] Elegir un nombre genial
- [x] Historia de usuario  
- [x] Estimación
- [x] Seleccion de historias
- [x] Definir alcance
### Planificación de una Iteración (Deberá existir 2 iteraciones del sistema)
- [x] Escribir Task Cards a partir de las Historias de Usuario
- [x] Entregar Selección y Estimación de Task Points en días.
### Programación
- [x] Modelo de dominio DER o Diagrama de Clases completo.
- [x] Spikes (entregadas con la documentación)
- [x] Casos de prueba en JUnit
- [x]  Usar Versionado 
- [x] se deberá identificar y entregar el código refactorizado (“code smells”).
